### PR TITLE
Add Zero Dark Matrix to extensions

### PR DESCRIPTION
**Pull request by tonybaroneee**
Adds the [Zero Dark Matrix](https://chrome.google.com/webstore/detail/devtools-theme-zero-dark/bomhdjeadceaggdgfoefmpeafkjhegbo) extension to the UX category. This is a popular dark theme for DevTools.

### CODE REVIEW

**Comment by Garbee** [comment]
This should just be under UX if it is included.

**Comment by tonybaroneee** [comment]
Yeah, I was debating that as well. Just moved it into UX since one other person thought so too :smile:

**Comment by samccone** [comment]
:boom: awesome @tonybaroneee thanks a million!

**Comment by tonybaroneee** [comment]
Cool, thank **you**!

**Pull request merged**
