### PR TITLE
Add my own silly chrome remote debugging project.

### PR DESCRIPTION
**Pull request by fake-name**
This is a PR to add the python remote debug protocol wrapper I've been poking about with for the last 8+ months or so.

It's half horrible python AST abuse, but it should allow the protocol wrapper to be regenerated on-the-fly for the active chromium version once https://codereview.chromium.org/2867073006/ (Chromium 60) lands.

At this point, I'm actively using it, and a lot of the higher-level automation is still under development, but as a convenient way to just use chromium ~~in a single-tab manner~~ (multiple tabs are present, very WIP), it's quite nice. I even have [docs](https://fake-name.github.io/ChromeController/ChromeController.ChromeRemoteDebugInterface.html)!

### CODE REVIEW

**Comment by fake-name** [comment]
I signed it!

**Comment by fake-name** [comment]
?

**Comment by paulirish** [comment]
@fake-name i am not very happy with having 4 python projects in here with fairly similar goals. However, I'm not a python developer, so I'm not in the best place to evaluate the strengths of each project. Can you suggest a project or two that i should remove in exchange for yours?

**Comment by fake-name** [comment]
Looking at them, I don't see them being that similar at all, really..

 - [`ChromeWhip`](https://github.com/chuckus/chromewhip) is the most similar to what my project implements, but they're seeking to re-implement a specific API, rather then just exposing the devtools API itself (which is my goal).
 - [`PyChrome`](https://github.com/fate0/pychrome) is much lower level, it primarily looks to allow calling arbitrary functions via the websocket transport.
 - [`PyChromeDevTools`](https://github.com/marty90/PyChromeDevTools) is very similar to `PyChrome`. 

Realistically, I could probably actually place my project on top of either PyChrome or PyChromeDevTools, using them as the underlying communication transport. However, I've also recently been putting a fair bit of work into the effort of managing executing chrome from python, and managing it's life-cycle and proper tear-down. From a quick skim of the other options, *none* of them do this. 

If I were forced to chose, I'd say that PyChrome and PyChromeDevTools very much replicate each-other more then the other projects.

Realistically, I'd group them into two groups: "Transport", which handle the banal internals of talking to chromium, but don't do things like function name/parameter checking, and "High-Level", which seek to expose the fully structured debugging interface in python. There's *another* transport chrome module [chrome_remote_shell](https://github.com/minektur/chrome_remote_shell), which I admit I actually started with as a base. 

I'd group PyChrome, PyChromeDevTools, and chrome_remote_shell as "transport" libraries, while ChromeWhip and my own project are "high-level" interface wrappers.

I'm not sure if this helps.

**Comment by paulirish** [comment]
@fake-name this does help. thanks for that breakdown.

**Comment by fake-name** [comment]
?

**Pull request closed without merging**
