### PR TITLE
Add buggerjs

### PR DESCRIPTION
**Pull request by derimagia**

### CODE REVIEW

**Comment by sidorares** [comment]
there probably should be a whole section for apps that pretend to be chrome and expose server side of the RDP so you can connect chrome devtools. (  https://github.com/kdzwinel/betwixt , node-inspector etc )

**Comment by derimagia** [comment]
That's a good idea, Since I was adding them 1 at a time I didn't do that yet but I could see that. Also, betwixt is already in there under a different category.

**Comment by sidorares** [comment]
and section for those that sit in the middle ( my crmux, other adaptors - http://remotedebug.org/adaptors/ )

**Comment by paulirish** [comment]
yeah i like the categorization ideas here. happy to merge if either of you want to PR it (after all these PRs get sorted out.. there's a few.)

**Pull request merged**
