### PR TITLE
Add link to Rust crate

### PR DESCRIPTION
**Pull request by atroche**
Thanks!

### CODE REVIEW

**Comment by atroche** [comment]
I signed it!

**Comment by Garbee** [comment]
I would like to see a more descriptive expression of the package. Rather than "A rust crate for the protocol" could we try to have something more like, "An implementation of puppeteer in Rust". Something along these lines is more descriptive of what readers can expect when they click through. Especially since it defines the protocol being replicated when we have multiple protocols for Chrome and the DevTools.

**Comment by atroche** [comment]
@Garbee thanks, how's that?

**Comment by Garbee** [comment]
Looks good to me, thank you.

**Pull request merged**
