### PR TITLE
Add Mare, A Lua debugger

### PR DESCRIPTION
**Pull request by muzuiget**
Mare, A Lua 5.3 Debugger, use DevTools as frontend

### CODE REVIEW

**Comment by Garbee** [comment]
I like showing off that the DevTools frontend can be used for languages beyond JS. This is super cool. But, I don't like the heading. Perhaps a new `Debugging other languages` section at the end should be added which can be an umbrella for any tools that use the frontend as an interface to other languages.

**Comment by muzuiget** [comment]
Heading had changed.

**Comment by Garbee** [comment]
LGTM.

@paulirish Do you have any issues with this new section?

Waiting for Paul to double-check this. Not sure if he expected this type of coverage when making the repo. It may be a bit due to I/O. Thank you in the mean time, it's cool to know other languages have build debugging tools on top of the DevTools interface.

**Comment by paulirish** [comment]
Awesome. yeah let's do this!

@muzuiget thanks for adding this! really cool

**Pull request merged**
