### PR TITLE
Added link in developing with dev tools

### PR DESCRIPTION
**Pull request by crislin2046**
I don't think you'll merge this PR because it looks like it's just promoting a commercial product.

I made a 'remote browser isolation' platform and share this free demo of it here. 

I heavily rely on Chrome devtools for this task so want to give back to the community by showing what's possible.

As I'm unwilling to release the source (because the full product is money-making) I'm quite sure you'll be unable to include it here.

### CODE REVIEW

**Comment by crislin2046** [comment]
@googlebot I signed it!

**Comment by Garbee** [comment]
I'll look in getting our contributing file updated to reflect our stance on this properly. My current understanding is that you are correct, we don't accept things that are free demos or paid services. The goal is to promote projects that others may use to better use the DevTools and learn how to work on the provided APIs in their own projects.

Unless something has changed in this regard (which we'll figure out shortly enough with my PR to the contributing file) this won't be pulled in. Closing this out for now and if we come to another decision after that discussion then we can re-open and merge.

Thank you.

**Comment by crislin2046** [comment]
Understood. Thanks for the thorough explanation @Garbee

**Comment by crislin2046** [comment]
Can I re-open?

Because it's now Open Sourced:

https://github.com/dosycorp/browsergap.ce

**Comment by Garbee** [comment]
I don't see why not now. Although I would say based on the current state of things I'd *prefer* a link to the github repo over the site directly since it doesn't seem to be updated to reference that. While the repo does link to the service that is online.

**Comment by crislin2046** [comment]
Sorry, that's what I meant. A link to the GitHub repo!

**Comment by crislin2046** [comment]
Hey @Garbee does this not LGTY?

**Comment by Garbee** [comment]
With that last text update it does. Sorry for delay, meant to comment the other day about that when I saw this in my notifications but work got overwhelming.

**Comment by crislin2046** [comment]
Thanks @Garbee !

**Pull request merged**
