### PR TITLE
Adding PuPHPeteer

### PR DESCRIPTION
**Pull request by spekulatius**
Hey @Garbee 

I feel [PuPHPeteer](https://github.com/rialto-php/puphpeteer), a PHP-bridge for Puppeteer would make a good addition. What do you think?

Cheers,
Peter

### CODE REVIEW

**Comment by Garbee** [comment]
The project looks good. My only concern is it is currently marked as seeking a new maintainer. Which has been the case since April 12th.

Looking the docs over, the API seems logical and sound as a PHP surface area. I however am going to defer inclusion to @paulirish since I personally think we should try to keep our list to actively maintained projects. As far as I recall this kind of thing hasn't come up before, so we have no existing precedent.

**Review by Garbee — APPROVED** [review]
Approving since the project does seem fine and the description is clear.

Still needs approval from Paul due to the maintenance status of the project before merge.

**Comment by spekulatius** [comment]
Hey @Garbee 

thanks for your reply. I'm actually assisting with the project - Johann and myself discussing next major version atm. Maybe I should have waited for the new version behind ready and removal of the message, just excited :)

Cheers,
Peter

**Comment by nesk** [comment]
Hi @Garbee,

I'm the original author of PuPHPeteer. I was, indeed, searching for a new maintainer but things are settled now: @spekulatius is joining me in the maintenance of the project! 🎉 We are both working on it now.

I've just removed the "searching for a new maintainer" banner. Currently, we are working on a v2 of the project, which will add support for the latest versions of Puppeteer and proper autocompletion in IDEs.

**Comment by Garbee** [comment]
Yup, LGTM then. Merging on in.

Just trying to make sure we aren't having stuff referenced that ends up un-maintained when there are clear signs up front that it could be a possibility.

**Comment by nesk** [comment]
I perfectly understand you don't want to add unmaintained projects. Thank you for merging! 😉

**Comment by spekulatius** [comment]
🎉️ Thank you @Garbee 🎉️

**Pull request merged**
