### PR TITLE
Add Bookmarks, History, Website DevTools Sidebar Panel

### PR DESCRIPTION
**Pull request by niutech**
https://github.com/niutech/chrome-devtools-sidebar

### CODE REVIEW

**Comment by niutech** [comment]
Done.

**Comment by Garbee** [comment]
Do you mind describing how this is beneficial to developers productivity? I don't see how this would provide enough benefit to most developers to include it in the listing.

Thank you.

**Comment by paulirish** [comment]
generally agree with @Garbee. we want to be selective here and i dont think this extension delivers enough value for devtools hardcore users.

thank you though!

**Comment by niutech** [comment]
It is simple: this extension allows you to open a mobile version of
the page you are developing in a sidebar, side-by-side.

**Comment by Garbee** [comment]
Mobile versions are best handled in Device Mode, not an iframed view within DevTools. Device Mode allows the engine to take into account meta viewport and other useful components from DevTools (such as geolocation and orientation emulation.) These all together provide a far more robust experience to developers to develop mobile applications than an iframed site copy alone.

**Pull request closed without merging**
