### PR TITLE
Add Ti Inspector

### PR DESCRIPTION
**Pull request by auchenberg**

### CODE REVIEW

**Comment by samccone** [comment]
Are we sure this still works? :) seems like it has been a while since it has been updated

**Comment by auchenberg** [comment]
No idea ;)  Just syncing with my list from RemoteDebug. I guess it would still work for the (few) Titanium apps that are out there?

**Comment by Garbee** [comment]
I think considering Titanium was deprecated in favor of Appcelerator a while ago we shouldn't add this one. It isn't useful to suggest extensions for outdated technologies.

Those apps that exist that use Titanium can find it, otherwise it doesn't seem to do much being in our list.

**Comment by auchenberg** [comment]
Titanium is fully alive, and actively maintained. https://github.com/appcelerator/titanium_mobile, as a part of the broader "appcelerator platform".

**Comment by Garbee** [comment]
ah, much design Appcelerator has. That is very difficult to find out navigating their site. :frowning:

LGTM then pending a better description. We want to avoid stating "with Chrome DevTools" and the like. It is fluff considering this repository is only about Chrome DevTools stuff.

**Comment by paulirish** [comment]
looks like this commit breaks formatting btw: 

image

**Comment by Garbee** [comment]
Yea, extra star on the line between the header causing that.

**Comment by auchenberg** [comment]
Fixed :)

**Comment by paulirish** [comment]
Sindre's guidance has been to be selective about the list so this might be one of the casualties.

Titanium is mostly out of favor these days so let's pass on this one.

**Pull request closed without merging**
