### PR TITLE
Add snapline

### PR DESCRIPTION
**Pull request by pmdartus**
CLI for extracting screenshots in timeline files and convert them to gif.

### CODE REVIEW

**Comment by samccone** [comment]
oh this is coooool, I wonder if a new timeline header is the right place for this...

**Comment by pmdartus** [comment]
I see what you mean, this tool consumes instead of producing data like all the other tools in the `CPU profile` category.

Maybe it could be interesting to put it under a new top level header `Process`? I can think of [node-big-rig](https://github.com/GoogleChrome/node-big-rig), that can also be added under this new header as well.

**Comment by samccone** [comment]
cc @paulirish for input

**Comment by paulirish** [comment]
This is more like a "presentation UX" item. Most people who would use it dont really care about timeline.

maybe "Multimedia" ?

**Comment by pmdartus** [comment]
Sounds good for me. :)

**Comment by Garbee** [comment]
Merged with commit 28cca4a73656b290e73c3fda85da8a7bb742db16.

Thank you!

**Pull request closed without merging**
