### PR TITLE
add link to crconsole

### PR DESCRIPTION
**Pull request by sidorares**
out

### CODE REVIEW

**Comment by derimagia** [comment]
It's actually in the bottom link https://developer.chrome.com/devtools/docs/debugging-clients (Not that I'm against also adding it to the list)

**Comment by sidorares** [comment]
@derimagia I had an impression that this repo is intended to mostly replicate https://developer.chrome.com/devtools/docs/debugging-clients

**Comment by paulirish** [comment]
yesss. definitely want to include crconsole. the description is much longer than most of what we have.. can you shorten it?

**Comment by sidorares** [comment]
yes, sorry, wasn't sure what to include. I'll rebase & shorten

**Comment by sidorares** [comment]
@paulirish done

**Comment by Garbee** [comment]
LGTM

**Comment by paulirish** [comment]
killer. thanks man!

**Pull request merged**
